import React from 'react';

function TopicsPage() {
    return (
        <>
            <h2>Web Development Concepts</h2>
            <nav class="local">
                <a href="#servers">Web Servers</a>
                <a href="#frontend">Frontend Design</a>
                <a href="#images">Optimizing Images</a>
                <a href="#favicons">Favicons</a>
            </nav>
            <article id="servers">
                <h3>Web Servers</h3>
                <p>For almost all web applications, the <strong>designated homepage</strong> on the web server is the <strong>index file</strong>. The index file is usually found by adding <strong>/index.html</strong> behind the web server name in the URL. Most web applications are designed to return the designated homepage, or index file, when a GET request is made for <strong>/</strong> rather than typing out the full /index.html. In the website's URL, this is the <strong>path to page</strong> or <strong>path to resource</strong> part that follows the server's name. Different servers may have different default names for the designated homepage. For example, on a Microsoft .NET server, the designated homepage is <strong>default.html</strong> rather than index.html. Further, a server could have a default homepage titled <strong>index.js</strong> or <strong>index.php</strong> if it is in a different language. For example, the js in index.js indicates that it would be in JavaScript.</p>
                <p>The browser’s web development or <strong>inspector</strong> network tab output screen displays the name of the files being used. Most importantly, it displays the <strong>index.html file</strong> of the web page that is being viewed. It may also include <strong>JavaScript files</strong>, <strong>CSS files</strong> and <strong>favicon files</strong>. When selecting the index.html file, general information about the page is displayed. This general information includes the <strong>request URL</strong>, the <strong>request method</strong>, the <strong>status code</strong>, and the <strong>IP address</strong>. The request method could be GET, PUT, or various other methods that represent the action the client is requesting. The status code could range from 100-599 depending on whether it is an informational response, successful response, redirection, client error or server error. In addition, the network tab will display the <strong>response headers</strong> and <strong>request headers</strong>. Several basic pieces of information displayed by the response header include the <strong>content type</strong> and the date the file was last modified. The request header includes information such as the language the page displays, the <strong>host name</strong> and the <strong>browser</strong> that is being used. When viewing the file from the web server versus the local computer, there is much more information provided for the file when viewed in the web server. For example, when inspecting the network details of the web server request there is an IP address, server, ETag, and cookies, while the file viewed from the local computer does not include these details. Details that they both display but are different include the request URL and the last-modified date based on when each file was last saved.  </p>
                <p>A <strong>status code</strong> of 200 indicates that the request for the file was successful, so when the <strong>favicon.ico</strong> displays 200 it means that it was successful. This success is apparent by the OSU COE icon that appears next to the title on the client tab. A status code of 404 indicates that there is a client error and that the file was not found. Therefore, this code indicates that the <strong>main.css</strong> and <strong>main.js</strong> files were not requested successfully. They were not requested successfully because the main.css and main.js files do not exist. </p>
                <p>My web server URL is  http://web.engr.oregonstate.edu/~ligonj. The http at the beginning of the URL is the <strong>scheme</strong> or the <strong>protocol</strong>, and it sends the request. Next, the <strong>server name</strong>, or <strong>host name</strong>, is web.engr.oregonstate.edu. The <strong>domain name</strong> is engr.oregonstate.edu. The domain name includes the <strong>subdomains</strong> engr and web that have been appended to the front of the domain name. Next, the <strong>port number</strong> has been omitted, so we can assume the server uses a default port number. Finally, the <strong>path to resource</strong>, ~ligonj, is at the end of the URL, and it identifies the resource on the server that is tied to my account.</p>
            </article>
            <article id="frontend">
                <h3>Frontend Design</h3>
                <p><strong>Frontend design</strong> is the design of what appears when a web application is accessed through a web server. This includes the <strong>design of the web application</strong>, the <strong>graphical user-interface</strong>, and how the user can <strong>interact with the web application</strong>. The web application design includes the visual attributes such as the colors, fonts, typography, photography, icons, and illustrations that appear. The graphical user-interface uses graphics or icons to allow the user to interact with the web application rather than just using text. Finally, the interactive experience includes how the user can interact with the web application and whether the web application allows for <strong>usability</strong> and <strong>inclusivity</strong>. </p>
                <dl>
                    <dt>Effective</dt>
                    <dd>The web application allows user to accurately meet their goal</dd>
                    <dt>Efficient</dt>
                    <dd>The web application allows user to complete their task quickly and in the fewest possible steps</dd>
                    <dt>Easy to Navigate</dt>
                    <dd>Navigation through the web application is intuitive and easy to repeat in the future</dd>
                    <dt>Error-Free</dt>
                    <dd>The web application doesn’t have any errors that stand in the way of the user completing their task or achieving their goal</dd>
                    <dt>Enjoyable/Engaging</dt>
                    <dd>The web application provides an overall positive experience that will bring the user back in the future</dd>
                </dl>
                <p><strong>Page layout tags</strong> are <strong>block-level elements</strong> that are used to organize the flow of the content in a web page. Several of these page layout tags or block-level elements are <strong>the header element</strong>, <strong>the main element</strong>, <strong>the section element</strong>, <strong>the article element</strong>, <strong>the footer element</strong> and <strong>the navigation element</strong>. The header element is used to display the banner for a web application and usually includes a name, publisher, or marketing slogan. The main element is used to denote the main area in which content is displayed. The section element is used to organize content within the main element. When there are different categories of concepts and multiple pieces of content for each category, a section should be created to organize the content. The article element is also used to organize content within main. It is an individual piece of content that can be used within a section or can stand alone if a section is not necessary in the organization of content. A footer element is used after the main element to display legal information, such as copyright information, contact information, and links to important pages. Finally, the navigation element is used to provide links to other pages of the web application so the user can move from the current page to another page and back to the starting page. </p>
                <ol>
                    <li><strong>Anchors to External Content</strong>:Anchors can be used to access external content. This can be done using the <strong>anchor tag</strong>. For example, inside the first anchor tag, you would define <strong>href</strong> as the URL you would like to link to. After the first anchor tag and before the closing anchor tag, you would enter the text you would like to see displayed and clicked on to access the URL.</li>
                    <li><strong>Anchors to Internal Content</strong>:Anchors can be used to access internal content. This can be done using an <strong>ID attribute</strong>. First, an ID is defined for the article. Next, the ID can be used with the anchor tag and href to anchor to a different article in the same page.</li>
                    <li><strong>Anchors from Page to Page</strong>:Anchors to navigate from page to page can be used with the navigation tag, anchor tag, href, and <strong>relative paths</strong>. Using a relative path means that the complete URL to the page is not used. Rather, the name of the file in the directory is used to reference the desired page. </li>
                </ol>
            </article>
            <article id="images">
                <h3>Optimizing Images</h3>
                <p>There are 6 specifications for optimizing images. First, images should be saved with descriptive file names so that they can be easily found by search engines. Second, they should be saved as small file sizes so that they can be loaded more quickly. <strong>Lossless compression</strong> can be used to compress the file size but maintain quality. Next, images should be sized to fit in the space allocated for the image in the webpage. Fourth, images should be saved as a file format that is best suited for the image type (photo, icon, graphic, etc.). Next, the resolution of the image should be reduced to fit the device on which it is being displayed. Since the images may be displayed on various devices, multiple files can be saved with different resolutions. Finally, the correct color mode should be used to optimize the image based on the file type.</p>
                <p><strong>JPG</strong> and <strong>WebP</strong> are two file formats that are best for photos and screenshots. JPGs and WebPs can be compressed for use on a webpage.  <strong>PNG</strong>, <strong>SVG</strong>, and <strong>GIF</strong> are three file formats that are well suited for line-art and animation. PNG can also be used for screenshots. PNG has true transparency, and the others have an option for transparency. SVGs and GIFs are commonly used for animation.</p>
            </article>
            <article id="favicons">
                <h3>Favicons</h3>
                <p><strong>Favicons</strong> are <strong>favorite icons</strong>, or <strong>touch icons</strong>, and are symbols that represent something such as a company, organization, school, or webpage. Favicons are displayed in a browser tab next to the title of the webpage that is displayed in the tab. They are also used as the icons that represent an application on a smartphone, tablet, or smartwatch. They are usually saved as <strong>ICO</strong>, SVG, and PNG files but can also be saved as GIF files.</p>
            </article>
</>
);
}
export default TopicsPage;